### ISSUE TITLE
Alma is not compatible with magento 2.4.4

### ISSUE THREAD

**Issue by amine-y** [alma/alma-monthlypayments-magento2#52]
I'm trying to upgrade to magento 2.4.4 and this error came up
I'm using alma 2.6.0
```BASH
Warning: Declaration of Alma\MonthlyPayments\Helpers\Logger::addRecord($level, $message, array $context = Array): bool should be compatible with Monolog\Logger::addRecord(int $level, string $message, array $context = Array, ?Monolog\DateTimeImmutable $datetime = NULL): bool in vendor/alma/alma-monthlypayments-magento2/Helpers/Logger.php on line 74

```

**Comment by webpar** [comment]
Hello,

Until an official fix is provided, in order to fix this issue, you'll need to update the file vendor/alma/alma-monthlypayments-magento2/Helpers/Logger.php and replace addRecord function declaration by : 
public function addRecord(int $level, string $message, array $context = [], \Monolog\DateTimeImmutable $datetime = null): bool

**Comment by amine-y** [comment]
@webpar Thanks that why already did

**Comment by Francois-Gomis** [comment]
Hello,
Thanks for your issue.
I prepare fix for the next version.

**Comment by sebfie** [comment]
Hello, I do not see it on master branch

**Comment by Francois-Gomis** [comment]
Hi,
new version is not yet published.

**Comment by sebfie** [comment]
Can you maybe just push on master :p
